import '@styles/global.css';
import Nav from '@components/Nav.js';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <Nav></Nav>
        {children}
      </body>
    </html>
  )
}
